- hosts: localhost
  vars:
     mysqlsize: "{{ mysqlsize | default(0) }}"
     amqsize: "{{ amqsize | default(0) }}"
     initdbsize: "{{ initdbsize | default(0) }}"
     gogssize: "{{ gogssize | default(0) }}"
  gather_facts: no
  tasks:
  - import_role:
      name: "initdb"
    when: initdbsize|int > 0
  - import_role:
      name: "mysql56"
    when: mysqlsize|int > 0
  - import_role:
      name: "amq"
    when: not amqsize|int == 0
  - import_role:
      name: "gogs"
    when: not gogssize|int == 0
